// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_id) VALUES ($1) RETURNING id, customer_id, created_at
`

func (q *Queries) CreateOrder(ctx context.Context, customerID int64) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, customerID)
	var i Order
	err := row.Scan(&i.ID, &i.CustomerID, &i.CreatedAt)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (product_id, order_id, quantity, price) VALUES ($1, $2, $3, $4) RETURNING id, product_id, order_id, quantity, price, created_at
`

type CreateOrderItemParams struct {
	ProductID int64 `json:"product_id"`
	OrderID   int64 `json:"order_id"`
	Quantity  int32 `json:"quantity"`
	Price     int32 `json:"price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.ProductID,
		arg.OrderID,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OrderID,
		&i.Quantity,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const findProductByID = `-- name: FindProductByID :one
SELECT id, name, price, quantity, created_at FROM products WHERE id = $1
`

func (q *Queries) FindProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, findProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerById = `-- name: GetCustomerById :one
SELECT id, name, email, phone_number, created_at FROM customers WHERE id = $1
`

func (q *Queries) GetCustomerById(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerById, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price, quantity, created_at FROM products
WHERE ($1 = '' OR name ILIKE '%' || $1 || '%')
ORDER BY name
`

func (q *Queries) ListProducts(ctx context.Context, dollar_1 interface{}) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET name = $2, price = $3, quantity = $4 WHERE id = $1 RETURNING id, name, price, quantity, created_at
`

type UpdateProductParams struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Price    int32  `json:"price"`
	Quantity int32  `json:"quantity"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Quantity,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}
